language: python
sudo: false
python:
  - "3.8"

install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#travis-ci
  - pip3 install bikeshed
  - bikeshed update

script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "65f8a8b9947d"
  - COMMIT_AUTHOR_EMAIL: "yoav@yoav.ws"
